apiVersion: v1
kind: Service
metadata:
  name: python-metrics-exporter
  namespace: monitoring
  labels:
    app: python-metrics-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 8080
      targetPort: 8080
  selector:
    app: python-metrics-exporter
