apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: artifactory-master-key
  namespace: artifactory
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: artifactory-master-key # Standard K8s secret generated automatically by ESO
    creationPolicy: Owner
  data:
    - secretKey: master-key
      remoteRef:
        key: secret/artifactory/keys
        property: master-key
    - secretKey: join-key
      remoteRef:
        key: secret/artifactory/keys
        property: join-key
