apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
type: Opaque
stringData:
  generic-webhook-url: "http://alertmanager-webhook.monitoring.svc:9093/api/v1/alerts"
  discord-webhook-url: "https://discord.com/api/webhooks/placeholder"
