# chart-values/argo-rollouts-values.yaml
controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

dashboard:
  enabled: true
  service:
    type: ClusterIP
    port: 3100
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi
