#chart-values/artifactory-values.yaml
global:
  masterKeySecretName: artifactory-master-key
  joinKeySecretName: artifactory-master-key

nginx:
  enabled: false

postgresql:
  enabled: true
  auth:
    username: artifactory
    database: artifactory
    password: "strongpassword"

artifactory:
  masterKeySecretName: artifactory-master-key
  joinKeySecretName: artifactory-master-key
  resources:
    requests:
      cpu: "500m"
      memory: "2Gi"
