persistence:
  enabled: true
  storageClass: "local-path"
  size: 10Gi

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    memory: 1.5Gi

livenessProbe:
  initialDelaySeconds: 180
  periodSeconds: 15
  failureThreshold: 6

readinessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 12

postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: postgres
    tag: "15-alpine"
