crds:
  install: true

admissionController:
  replicas: 1
  resources:
    limits:
      memory: 384Mi
    requests:
      cpu: 100m
      memory: 128Mi

backgroundController:
  replicas: 1

reportsController:
  replicas: 1

# Disable the cleanup deployment & background report jobs
reportsCleanup:
  image:
    repository: bitnami/kubectl
    tag: latest

features:
  logging:
    format: text
  cleanupServer:
    enabled: false
