apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # Source 1: Helm Chart with CRDs explicitly enabled
    - repoURL: "https://charts.external-secrets.io"
      chart: external-secrets
      targetRevision: 0.9.x
      helm:
        valueFiles:
          - "$values/chart-values/external-secrets-values.yaml"
        parameters:
          - name: installCRDs
            value: "true"

    # Source 2: Values Reference repository alias
    - repoURL: "https://github.com/davidjirca/k8s-platform-gitops.git"
      targetRevision: HEAD
      ref: values

    # Source 3: Raw manifests (ClusterSecretStore)
    - repoURL: "https://github.com/davidjirca/k8s-platform-gitops.git"
      targetRevision: HEAD
      path: raw-manifests/external-secrets
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
