apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: "https://stakater.github.io/stakater-charts"
      chart: reloader
      targetRevision: 1.x.x
      helm:
        valueFiles:
          - "$values/chart-values/reloader-values.yaml"
    - repoURL: "https://github.com/davidjirca/k8s-platform-gitops.git"
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: reloader
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
