apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # Source 1: Helm Chart
    - repoURL: "https://argoproj.github.io/argo-helm"
      chart: argo-rollouts
      targetRevision: 2.38.x
      helm:
        valueFiles:
          - "$values/chart-values/argo-rollouts-values.yaml"
    # Source 2: Values Reference
    - repoURL: "https://github.com/davidjirca/k8s-platform-gitops.git"
      targetRevision: HEAD
      ref: values
    # Source 3: AnalysisTemplates & Canary Workload
    - repoURL: "https://github.com/davidjirca/k8s-platform-gitops.git"
      targetRevision: HEAD
      path: raw-manifests/rollouts
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo-rollouts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
